version: "3.5"

services:
  mysql:
    image: mysql
    build: ./mysql
    ports:
      - "127.0.0.1:3306:3306"
    restart: always
    hostname: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    container_name: mysql
    volumes:
      - ${DATA_DIR}/mysql:/var/lib/mysql
